GENERAR DATASET USANDO PANDAS

In [22]:
import pandas as pd
import kagglehub

path = kagglehub.dataset_download("shayanzk/imdb-top-100-movies-dataset-2025-edition")
file = path + "/top_100_movies_full_best_effort.csv"

df = pd.read_csv(file)
df.drop(columns=["Title","Main Actor(s)", "Director","Country","Language"], inplace=True)
df.head()

,Rank,Year,Genre(s),IMDb Rating,Rotten Tomatoes %,Runtime (mins),Oscars Won,Box Office ($M),Metacritic Score
0,1,1994,Drama,9.3,91.0,142.0,0,58.0,82.0
1,2,1972,Crime|Drama,9.2,98.0,175.0,3,246.1,100.0
2,3,2008,Action|Crime|Drama,9.0,94.0,152.0,2,1004.9,84.0
3,4,1974,Crime|Drama,9.0,97.0,202.0,6,48.5,90.0
4,5,1957,Crime|Drama,9.0,100.0,96.0,0,1.0,96.0

ENCODING DE CADENAS DE TEXTO

In [23]:
# One-hot encoding de las columnas "Genre(s)", "Director", "Language" y "Country"
dummies = pd.concat([df[col].str.get_dummies(sep='|') for col in ['Genre(s)']], axis=1)
df = df.join(dummies).drop(columns=['Genre(s)'])

CONVERTIR A MATRIZ NUMPY

In [24]:
import numpy as np

X = df.to_numpy()

In [25]:
df.head()

,Rank,Year,IMDb Rating,Rotten Tomatoes %,Runtime (mins),Oscars Won,Box Office ($M),Metacritic Score,Action,Adventure,...,Horror,Music,Mystery,Romance,Satire,Sci-Fi,Sport,Thriller,War,Western
0,1,1994,9.3,91.0,142.0,0,58.0,82.0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1972,9.2,98.0,175.0,3,246.1,100.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,2008,9.0,94.0,152.0,2,1004.9,84.0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1974,9.0,97.0,202.0,6,48.5,90.0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1957,9.0,100.0,96.0,0,1.0,96.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
print(X)

[[1.000e+00 1.994e+03 9.300e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.000e+00 1.972e+03 9.200e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [3.000e+00 2.008e+03 9.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [9.800e+01 1.944e+03 8.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [9.900e+01 1.977e+03 8.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+02 1.959e+03 8.200e+00 ... 0.000e+00 0.000e+00 0.000e+00]]

In [29]:
#Muestra todos los generos que existen en el dataset
genre_columns = [col for col in df.columns if df[col].isin([0,1]).all()]

print(genre_columns)

['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Drama', 'Family', 'Fantasy', 'Film-Noir', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Satire', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'Western']

CLASIFICAR EN UN ARBOL DE DECISIÓN